k_search: 50
min_cluster_size: 50
max_cluster_size: 100000000
number_of_neighbours: 500
distance_of_neighbours: 0.0001
smoothness_threshold_rad: 0.5 #30deg
curvature_threshold: 0.02 #0.02  #2e = 0.02
residual_threshold: 0.03 # 3e = 0.03
smooth_mode_flag: true
curvature_test_flag: true
residual_test_flag: true
output_dir: /home/aichi2204/ros2_ws/test/pcl-test/data/map_all_removed/best
is_coloring: false